apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: JOB_SCHEDULER
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/namespaces/(.*)/jobs
        pathType: Prefix
        backend:
          service:
            name: JOB_SCHEDULER
            port:
              number: PORT
      - path: /api/v1/namespaces/(.*)/jobs/(.*)
        pathType: Prefix
        backend:
          service:
            name: JOB_SCHEDULER
            port:
              number: PORT
      - path: /api/v1/heartbeat
        pathType: Prefix
        backend:
          service:
            name: JOB_SCHEDULER
            port:
              number: PORT
      - path: /api/v1/health
        pathType: Prefix
        backend:
          service:
            name: JOB_SCHEDULER
            port:
              number: PORT

