load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "trans",
    srcs = glob(["*.py"]),
    deps = [
        "//neursafe_fl/proto",
    ],
    visibility = ["//visibility:public"],
)