load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "compression",
    srcs = glob(["**/*.py"]),
    deps = [
        "//neursafe_fl/python/runtime:base",
    ],
    visibility = ["//visibility:public"],
)