name: Build wheel packages 

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_whl:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python Env
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Install bazel build tool
        run: |
           curl -fSsL -O https://github.com/bazelbuild/bazel/releases/download/3.5.0/bazel-3.5.0-installer-linux-x86_64.sh && chmod +x bazel-*.sh && sudo ./bazel-3.5.0-installer-linux-x86_64.sh

      - name: Build wheel packages
        run: |
           pwd && ls ./
           source deploy/scripts/const.properties
           bazel build $client_bazel_obj $sdk_bazel_obj $coordinator_bazel_obj $job_scheduler_bazel_obj $cli_bazel_obj $selector_bazel_obj

      - name: Check wheel packages
        run: |
           source deploy/scripts/const.properties
           python3.7 -m pip install --upgrade --disable-pip-version-check $client_whl $sdk_whl $coordinator_whl $job_scheduler_whl $cli_whl $selector_whl
