name: Build docker images

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docker_images:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Build images
        run: |
           bash ./deploy/scripts/build_images.sh

